### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by darrenmayburn** [wusui/mad_as_a_march_aardvark#2]
Works for me to a point but runs into an issue as soon as it clicks into the bracket, citing and IndexError. Here's the Traceback I keep getting:

> Traceback (most recent call last):
>   File "C:\Users\brend\Documents\mad_as_a_march_aardvark-main\madness.py", line 11, in <module>
>     find_future_outcomes()
>   File "C:\Users\brend\Documents\mad_as_a_march_aardvark-main\find_future_outcomes.py", line 160, in find_future_outcomes
>     json.dump(gen_comparisons(), file, ensure_ascii=False)
>   File "C:\Users\brend\Documents\mad_as_a_march_aardvark-main\find_future_outcomes.py", line 74, in gen_comparisons
>     panswers = gen_panswers(len(all_results[0]))
>   File "C:\Users\brend\Documents\mad_as_a_march_aardvark-main\find_future_outcomes.py", line 62, in gen_panswers
>     panswers[pandp[0]] = pandp[1].split("|")[-gms_left:]
> IndexError: list index out of range

I should note that the script seemed to work correctly (or at least start) when I tested it out on a large, public ESPN "Fans of..." group, but when I tried it on two private groups (including "Mad as a March Llama") I got the above error every time.

**Comment by wusui** [comment]
Hi.  I just got back to looking at some of my past repositories.  I am not sure what's happening here but I ran into issues with my code recently.  I suspect that this is due to the tournament being complete and some parts of the code make the assumption that there are still games to be played.  I will probably not be touching this code until we approach tournament time next year, but I'll keep this in mind then.  Thanks for the input.
